services:
  wyoming_openai:
    image: ghcr.io/roryeckel/wyoming_openai:latest
    container_name: wyoming_openai
    ports:
      - "10300:10300"
    restart: unless-stopped
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
      WYOMING_LANGUAGES: en
      STT_OPENAI_URL: https://api.openai.com/v1
      STT_MODELS: "whisper-1 gpt-4o-mini-transcribe gpt-4o-transcribe"
      STT_BACKEND: "OPENAI"
      TTS_OPENAI_URL: https://api.openai.com/v1
      TTS_MODELS: "tts-1 tts-1-hd gpt-4o-mini-tts"
      TTS_BACKEND: "OPENAI"
      # TTS_VOICES: "alloy ash coral echo fable onyx nova sage shimmer"
      TTS_SPEED: "1.0"
    env_file:
      - .env
