services:
  wyoming_openai:
    build: .
    container_name: wyoming_openai
    ports:
      - "10300:10300"
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
      WYOMING_LANGUAGES: en
      STT_OPENAI_URL: http://speaches:8000/v1
      STT_MODELS: "Systran/faster-distil-whisper-large-v3"
      TTS_OPENAI_URL: http://speaches:8000/v1
      TTS_MODELS: "hexgrad/Kokoro-82M"
      TTS_VOICES: "af af_bella af_sarah am_adam am_michael bf_emma bf_isabella bm_george bm_lewis af_nicole af_sky" # http://speaches:8000/docs#/speech-to-text/list_voices_v1_audio_speech_voices_get

  speaches:
    container_name: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - enable_ui=False
      - log_level=info
      - WHISPER__MODEL=Systran/faster-distil-whisper-large-v3
      - WHISPER__compute_type=int8_float32
    volumes:
      - huggingface-hub:/home/ubuntu/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    runtime: nvidia

volumes:
  huggingface-hub:
