services:
  wyoming_openai:
    image: ghcr.io/roryeckel/wyoming_openai:main
    container_name: wyoming_openai
    ports:
      - "10300:10300"
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
      WYOMING_LANGUAGES: en
      STT_OPENAI_URL: https://api.openai.com/v1
      STT_MODELS: "whisper-1"
      TTS_OPENAI_URL: https://api.openai.com/v1
      TTS_MODELS: "tts-1 tts-1-hd"
      TTS_VOICES: "alloy echo fable onyx nova shimmer" # https://platform.openai.com/docs/guides/text-to-speech/voice-options
    env_file:
      - .env
