services:
  wyoming_openai:
    build: .
    container_name: wyoming_openai
    ports:
      - "10300:10300"
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
    env_file:
      - .env