services:
  wyoming_elevenlabs:
    image: ghcr.io/roryeckel/wyoming_elevenlabs:latest
    container_name: wyoming_elevenlabs
    ports:
      - "10300:10300"
    restart: unless-stopped
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
      WYOMING_LANGUAGES: en
      STT_ELEVENLABS_URL: https://api.elevenlabs.com/v1
      STT_MODELS: "gpt-4o-transcribe gpt-4o-mini-transcribe whisper-1"
      STT_BACKEND: "ELEVENLABS"
      TTS_ELEVENLABS_URL: https://api.elevenlabs.com/v1
      TTS_MODELS: "gpt-4o-mini-tts tts-1-hd tts-1"
      TTS_BACKEND: "ELEVENLABS"
      # TTS_VOICES: "alloy ash coral echo fable onyx nova sage shimmer"
      TTS_SPEED: "1.0"
    env_file:
      - .env
