services:
  wyoming_openai:
    image: ghcr.io/roryeckel/wyoming_openai:latest
    container_name: wyoming_openai
    ports:
      - "10300:10300"
    restart: unless-stopped
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
      WYOMING_LANGUAGES: en
      STT_OPENAI_URL: http://speaches:8000/v1
      STT_MODELS: "Systran/faster-distil-whisper-large-v3"
      STT_BACKEND: "SPEACHES"
      TTS_OPENAI_URL: http://speaches:8000/v1
      TTS_MODELS: "speaches-ai/Kokoro-82M-v1.0-ONNX"
      TTS_BACKEND: "SPEACHES"
      # TTS_VOICES: "af af_bella af_sarah am_adam am_michael bf_emma bf_isabella bm_george bm_lewis af_nicole af_sky"
    depends_on:
      speaches:
        condition: service_healthy

  # https://speaches.ai/usage/text-to-speech/
  init-speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    container_name: init-speaches
    environment:
      - SPEACHES_BASE_URL=http://speaches:8000
    command: >
      /bin/bash -c '
        curl -LsSf https://astral.sh/uv/install.sh | sh # https://github.com/speaches-ai/speaches/issues/416
        uvx speaches-cli model download speaches-ai/Kokoro-82M-v1.0-ONNX
        uvx speaches-cli model download Systran/faster-distil-whisper-large-v3
      '
    volumes:
      - huggingface-hub:/home/ubuntu/.cache/huggingface/hub
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    depends_on:
      speaches: # Seems backwards but the API is not yet available
          condition: service_healthy

  speaches:
    container_name: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - enable_ui=False
      - log_level=info
      - WHISPER__MODEL=Systran/faster-distil-whisper-large-v3
      - WHISPER__compute_type=int8_float32
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - huggingface-hub:/home/ubuntu/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    runtime: nvidia

volumes:
  huggingface-hub: